webpack.config.js

Remove tslib from webpack.config externals

Remove tslib from externals

---

README.md
package-lock.json
src/sdk/model/domain-permission-map.ts
src/sdk/model/json/policy.ts
src/sdk/model/policy.ts
src/sdk/model/role-creation-request.ts
src/sdk/model/role.ts
src/sdk/model/user-with-security.ts
src/sdk/service/__tests__/iam-service.test.unit.ts
src/sdk/service/__tests__/permission-service.test.unit.ts
src/sdk/service/iam-service.ts
src/sdk/service/permission-service.ts

Reverts ilanddev/javascript-sdk#22

Revert "Fix issue"

---

src/sdk/api-error.ts
src/sdk/http.ts

otherwise throws a runtime error

handle connection errors

---

src/sdk/__mocks__/http.ts
src/sdk/__mocks__/responses/vpg/vpg.ts
src/sdk/model/vpg/__tests__/vpg.test.int.ts
src/sdk/model/vpg/__tests__/vpg.test.unit.ts
src/sdk/model/vpg/json/perf-sample-serie.ts
src/sdk/model/vpg/json/vpg-checkpoint.ts
src/sdk/model/vpg/json/vpg-failover-create-request.ts
src/sdk/model/vpg/json/vpg-failover-report-detail.ts
src/sdk/model/vpg/json/vpg-failover-test-alert-request.ts
src/sdk/model/vpg/json/vpg-failover-test-alert.ts
src/sdk/model/vpg/json/vpg-sub-entity-request.ts
src/sdk/model/vpg/json/vpg.ts
src/sdk/model/vpg/perf-sample-serie.ts
src/sdk/model/vpg/service-profile.ts
src/sdk/model/vpg/vpg-checkpoint.ts
src/sdk/model/vpg/vpg-entities.ts
src/sdk/model/vpg/vpg-failover-create-request.ts
src/sdk/model/vpg/vpg-failover-report-details.ts
src/sdk/model/vpg/vpg-failover-test-alert-request.ts
src/sdk/model/vpg/vpg-failover-test-alert.ts
src/sdk/model/vpg/vpg-vm.ts
src/sdk/model/vpg/vpg.ts

add vpg endpoints

---

src/sdk/__mocks__/http.ts
src/sdk/__mocks__/responses/vdc/vdc.ts
src/sdk/model/__tests__/vdc.test.unit.ts
src/sdk/model/vdc.ts

vdc metadata endpoints

---

src/sdk/model/mixins/perf-samples/_json_/perf-samples-request.ts
src/sdk/model/mixins/perf-samples/_json_/perf-samples.ts
src/sdk/model/mixins/perf-samples/_tests_/perf-sample.test.unit.ts
src/sdk/model/mixins/perf-samples/entity-with-perf-samples.ts
src/sdk/model/mixins/perf-samples/perf-counter.ts
src/sdk/model/mixins/perf-samples/perf-sample.ts
src/sdk/model/mixins/perf-samples/perf-samples-request.ts
src/sdk/model/mixins/perf-samples/perf-samples-series.ts
src/sdk/model/vapp/__mocks__/vapp.ts
src/sdk/model/vapp/__tests__/vapp.test.int.ts
src/sdk/model/vapp/__tests__/vapp.test.unit.ts
src/sdk/model/vapp/vapp.ts
src/sdk/model/vdc/__mocks__/vdc.ts
src/sdk/model/vdc/__tests__/vdc.test.int.ts
src/sdk/model/vdc/__tests__/vdc.test.unit.ts
src/sdk/model/vdc/vdc.ts
src/sdk/model/vm/__mocks__/vm.ts
src/sdk/model/vm/__tests__/vm.test.int.ts
src/sdk/model/vm/__tests__/vm.test.unit.ts
src/sdk/model/vm/vm.ts
src/sdk/service/http/__mocks__/http.ts
tslint.json

31: Add perf samples endpoints

---

src/sdk/model/media/__json__/index.ts
src/sdk/model/media/__json__/media-clone-request.ts
src/sdk/model/media/__json__/media-update-request.ts
src/sdk/model/media/__tests__/media.test.unit.ts
src/sdk/model/media/media-clone-request.ts
src/sdk/model/media/media-update-request.ts
src/sdk/model/media/media.ts
src/sdk/model/task/__json__/task-operation-type.ts
src/sdk/service/http/__mocks__/http.ts

46: Add Media Endpoint

---

src/sdk/model/user/__tests__/user-with-security.test.unit.ts
src/sdk/model/user/__tests__/user.test.unit.ts
src/sdk/model/user/user.ts
src/sdk/service/http/__mocks__/http.ts

#66 Add full role management to user class

---

src/sdk/model/user/__json__/index.ts
src/sdk/model/user/__json__/user-creation-request-json.ts
src/sdk/model/user/__json__/user-domain-json.ts
src/sdk/model/user/__json__/user-domain-type.ts
src/sdk/model/user/__json__/user-json.ts
src/sdk/model/user/__json__/user-update-request-json.ts
src/sdk/model/user/__mocks__/user.ts
src/sdk/model/user/__tests__/user.test.unit.ts
src/sdk/model/user/index.ts
src/sdk/model/user/user-update-request.ts
src/sdk/model/user/user.ts
src/sdk/service/http/__mocks__/http.user.ts

Update user class to add update and delete.

---

src/sdk/model/vapp/__tests__/vapp.test.unit.ts
src/sdk/model/vapp/vapp.ts
src/sdk/service/http/__mocks__/http.vapp.ts

Add metadata support for vapp.

---

src/sdk/model/vm/__tests__/vm.test.unit.ts
src/sdk/model/vm/vm.ts

Resolves #169: Fix VM metadata update

Resolves #169: Fix vm metadata update

---

tsconfig.json

Fixes the issue with the duplicate AxiosResponse import that we see when building the console

fix d.ts file build

---

src/sdk/model/company/__json__/company-json.ts
src/sdk/model/company/__mocks__/company.ts
src/sdk/model/company/__tests__/company.test.unit.ts
src/sdk/model/company/company.ts

added object storage to company

---

src/sdk/model/company/support-ticket/support-ticket.ts

fix add ticket attachment endpoint

---

src/sdk/model/vapp/__json__/vapp-json.ts
src/sdk/model/vapp/__mocks__/vapp.ts
src/sdk/model/vapp/__tests__/vapp.test.int.ts
src/sdk/model/vapp/__tests__/vapp.test.unit.ts
src/sdk/model/vapp/vapp.ts
src/sdk/model/vm/__json__/vm-json.ts
src/sdk/model/vm/__mocks__/vm.ts
src/sdk/model/vm/__tests__/vm.test.int.ts
src/sdk/model/vm/__tests__/vm.test.unit.ts
src/sdk/model/vm/vm.ts

#337 add allocation model field

add allocation model to vapp and vm json response

---

src/sdk/model/edge/ipsec-vpn/__json__/edge-ipsec-vpn-json.ts
src/sdk/model/edge/ipsec-vpn/__json__/global-settings-json.ts
src/sdk/model/edge/ipsec-vpn/__json__/ip-sec-vpn-site-json.ts
src/sdk/model/edge/ipsec-vpn/__json__/logging-settings-json.ts
src/sdk/model/edge/ipsec-vpn/__mocks__/edge-ipsec-vpn.ts
src/sdk/model/edge/ipsec-vpn/__tests__/ipsec-vpn.test.unit.ts
src/sdk/model/edge/ipsec-vpn/ip-sec-vpn-site.ts
src/sdk/model/edge/ipsec-vpn/ipsec-vpn.ts

fix ipsec vpn response object

---

src/sdk/model/common/__json__/network-ip-scope-json.ts
src/sdk/model/common/network-ip-scope.ts

I've made optionals fields optionals again.

Fix network ip-scope request object.

---

src/sdk/model/vdc/__json__/vm-affinity-rule-json.ts
src/sdk/model/vdc/vm-affinity-rule.ts

- Remove old fields
- Expose is_mandatory field

IP-3668: Fixes for vm-affinity rule implementation

---

src/sdk/model/vac/__json__/ba-company.ts
src/sdk/model/vac/ba-company.ts

@SuperConfuserUser @ariquinones @fradinni  Can i get a + 1 on this one please ?

Adding one missing field to BaCompany

---

src/sdk/model/company/__json__/cloud-tenant-bill-json.ts
src/sdk/model/company/cloud-tenant-bill.ts

Add extra params for vcc billing bill.

---

src/sdk/model/task/__json__/task-operation-type.ts
src/sdk/model/task/__json__/task-type.ts

@cfsnyder @SuperConfuserUser @ariquinones @fradinni Can i have a +1 on this one please ?

Add missing tasks types and operation types.

---

package-lock.json
package.json
src/sdk/auth/browser-auth-provider.ts

Once merged these code changes will break integration tests until Keycloak v9 is updated in Prod since tests are running against prod instance.

Update keycloak-js to version 9.0.0

---

src/sdk/model/o365/__json__/o365-organization-json.ts
src/sdk/model/o365/o365-organization.ts

platform PRs:
- [new fields](http://git.iland.test/projects/IC/repos/iland-core/pull-requests/4453/diff#model/src/main/java/com/iland/core/api/vbo/O365Organization.java)
- [deprecated fields](http://git.iland.test/projects/IC/repos/iland-core/pull-requests/4455/diff#web-v1/rest-api/public-api/src/main/java/com/iland/core/web/rest/response/vbo/O365OrganizationResponse.java)

update O365 org model user count fields

---

src/sdk/model/o365/__json__/o365-organization-json.ts
src/sdk/model/o365/o365-organization.ts

[swagger doc](http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getOrganization) | [platform pr](http://git.iland.test/projects/IC/repos/iland-core/pull-requests/4464/diff#web-v1/rest-api/public-api/src/main/java/com/iland/core/web/rest/response/vbo/O365OrganizationResponse.java)

add new numberOfReservedLicenses field to O365 Org model

---

src/sdk/model/o365/__json__/o365-organization-json.ts
src/sdk/model/o365/__json__/o365-user-json.ts
src/sdk/model/o365/o365-organization.ts
src/sdk/model/o365/o365-user.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getOrganization

Added number of licenses used field to O365 Org model & licensed field to O365 User model.

---

src/sdk/model/vdc/__json__/storage-profile-bill-json.ts
src/sdk/model/vdc/vdc-storage-profile-bill.ts

swagger doc: http://doc.10.api.iland.test/1.0/#/vDCs/getStorageProfileSummary

add zerto storage values to vdc storage profile bill

---

src/sdk/model/o365/__json__/o365-modify-credentials-request-json.ts
src/sdk/model/o365/o365-modify-credentials-request.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/modifyOrganizationCredentials

Add new fields to O365 modify credentials model for modern auth usage

---

src/sdk/model/company/__json__/o365-org-create-request-json.ts
src/sdk/model/company/o365-org-create-request.ts

http://doc.10.api.iland.test/1.0/#/Companies/createO365Organization

Add new fields to O365 create org model for modern auth usage

---

src/sdk/model/company/__json__/o365-org-create-request-json.ts
src/sdk/model/company/o365-org-create-request.ts

http://doc.10.api.iland.test/1.0/#/Companies/createO365Organization

Add teams and remove repo id fields for o365 create org model

---

src/sdk/model/o365/__json__/o365-modify-credentials-request-json.ts
src/sdk/model/o365/__json__/o365-organization-json.ts
src/sdk/model/o365/o365-modify-credentials-request.ts
src/sdk/model/o365/o365-organization.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getOrganization
http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/modifyOrganizationCredentials

Add teams field to O365 org & modify credentials models

---

src/sdk/model/sso/__json__/oidc-prompt-type.ts

Lowercase OIDCPrompt Enum values to reflect API changes

IP-4426: Update OIDC Promp Enum

---

src/sdk/model/o365/__json__/o365-create-job-request-json.ts
src/sdk/model/o365/o365-create-job-request.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/createO365Job

Remove repo id from O365 create job model

---

src/sdk/model/o365/__json__/o365-job-json.ts
src/sdk/model/o365/__json__/o365-restore-session-json.ts
src/sdk/model/o365/o365-job.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/startRestoreSession
http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getJobByUuid

Add Teams for O365 start restore session

---

src/sdk/model/o365/__json__/o365-marked-purge-mailbox-json.ts
src/sdk/model/o365/o365-marked-purge-mailbox.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getPurgeMailboxes

Add completed date field for O365 purge mailboxes

---

src/sdk/model/company/__json__/o365-bill-json.ts
src/sdk/model/company/o365-bill.ts
src/sdk/model/o365/__json__/o365-organization-json.ts
src/sdk/model/o365/o365-organization.ts

http://doc.10.api.iland.test/1.0/#/Companies/getO365BillingHistory
http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getOrganization

Add new licensing info fields for O365 Org and Billing

---

src/sdk/model/o365/__json__/o365-restore-session-start-request-json.ts
src/sdk/model/o365/o365-restore-session-start-request.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/startRestoreSession

Update show_delete field for O365 Create restore session

---

src/sdk/model/company/__json__/company-json.ts
src/sdk/model/company/company.ts

[core update](http://git.iland.test/projects/IC/repos/iland-core/pull-requests/4823/diff#web-v1/rest-api/public-api/src/main/java/com/iland/core/web/rest/response/company/CompanyResponse.java)

add has_ceph field to company model

---

src/sdk/model/o365/__json__/o365-sharepoint-restore-options-request-json.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/restoreSharePointSiteTo

Update O365 SharePoint Document Version enum(s) values

---

src/sdk/model/o365/__json__/o365-job-json.ts
src/sdk/model/o365/o365-job.ts

http://doc.10.api.iland.test/1.0/#/Office%20365%20Backup/getJobByUuid

Add is_restore_session_exist field to O365 job model

---

src/sdk/model/vpg/expanded-vpg.ts

bringing in [this tiny change](https://github.com/ilanddev/javascript-sdk/pull/619) from zerto billing beta

Fix expanded vpg service profile getter

---

src/sdk/model/org/__json__/dns-record-create-request-json.ts
src/sdk/model/org/__json__/dns-record-update-request-json.ts
src/sdk/model/org/dns-record-create-request.ts
src/sdk/model/org/dns-record-update-request.ts

http://doc.10.api.iland.test/1.0/#/Organizations/addDNSRecord
The field that needs to be provided is 'ip' instead of 'ip_address' per the model doc 'title: ip'

Update DNS Record create request ip field

---

src/sdk/model/org/__json__/dns-record-update-request-json.ts
src/sdk/model/org/dns-record-update-request.ts

http://doc.10.api.iland.test/1.0/#/Organizations/updateDNSRecord
ip_address for update and just ip for create

Update DNS Record update request ip field

---

src/sdk/model/vm/guest-tools/__json__/guest-tools-json.ts
src/sdk/model/vm/guest-tools/__mocks__/guest-tools.ts
src/sdk/model/vm/guest-tools/guest-tools.ts

enum constants for version status & running status:
https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vm.GuestInfo.ToolsVersionStatus.html
https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vm.GuestInfo.ToolsRunningStatus.html

Add Vm GuestTools status enums

---

src/sdk/model/media/media.ts

- Updated the method to be consistent with the other entities (vApp, vDC, Catalog etc.)
- Fixes bad request from UI Entity Metadata Modal

Update the Media updateMetadata method
